# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(440, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StartWindow.sizePolicy().hasHeightForWidth())
        StartWindow.setSizePolicy(sizePolicy)
        StartWindow.setMinimumSize(QtCore.QSize(440, 220))
        StartWindow.setMaximumSize(QtCore.QSize(440, 220))
        self._centralwidget = QtWidgets.QWidget(StartWindow)
        self._centralwidget.setObjectName("_centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self._centralwidget)
        self.verticalLayout.setContentsMargins(30, 15, 30, 15)
        self.verticalLayout.setObjectName("verticalLayout")
        self._title = QtWidgets.QLabel(self._centralwidget)
        self._title.setObjectName("_title")
        self.verticalLayout.addWidget(self._title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self._horizontalLayout = QtWidgets.QHBoxLayout()
        self._horizontalLayout.setObjectName("_horizontalLayout")
        self._label = QtWidgets.QLabel(self._centralwidget)
        self._label.setObjectName("_label")
        self._horizontalLayout.addWidget(self._label)
        self._pathText = QtWidgets.QLineEdit(self._centralwidget)
        self._pathText.setObjectName("_pathText")
        self._horizontalLayout.addWidget(self._pathText)
        self._searchButton = QtWidgets.QPushButton(self._centralwidget)
        self._searchButton.setEnabled(True)
        self._searchButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self._searchButton.setObjectName("_searchButton")
        self._horizontalLayout.addWidget(self._searchButton)
        self.verticalLayout.addLayout(self._horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self._buttonBox = QtWidgets.QDialogButtonBox(self._centralwidget)
        self._buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self._buttonBox.setObjectName("_buttonBox")
        self.verticalLayout.addWidget(self._buttonBox)
        StartWindow.setCentralWidget(self._centralwidget)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Semantics Analyzer"))
        self._title.setText(_translate("StartWindow", "Select a directory as a workspace"))
        self._label.setText(_translate("StartWindow", "Workspace: "))
        self._searchButton.setText(_translate("StartWindow", "..."))
